#!/bin/bash
# Quick deployment script for Render.com

echo "🚀 Hospital Meals - Render Deployment Helper"
echo "=============================================="
echo ""
echo "Prerequisites:"
echo "1. GitHub account"
echo "2. Render.com account (free)"
echo ""
echo "Step 1: Initialize Git Repository"
git init
git add .
git commit -m "Initial commit - Hospital Meals Management System"
echo ""
echo "Step 2: Create GitHub Repository"
echo "- Go to https://github.com/new"
echo "- Create a repository named 'hospital-meals'"
echo "- Follow the instructions to push this code"
echo ""
echo "Step 3: Deploy on Render"
echo "- Visit https://render.com"
echo "- Sign up with GitHub"
echo "- Click 'New +' → 'Web Service'"
echo "- Connect 'hospital-meals' repository"
echo ""
echo "Step 4: Configure Deployment"
echo "- Build Command: npm ci"
echo "- Start Command: npm start"
echo "- Plan: Free"
echo ""
echo "Step 5: Add Environment Variables"
echo "- NODE_ENV=production"
echo "- JWT_SECRET=<generate-strong-secret>"
echo "- PORT=3000"
echo ""
echo "✅ Done! Your app will be live in 5-10 minutes"
echo "Visit: https://hospital-meals.onrender.com"
